# Nombre de la aplicacion
spring.application.name=jobfree-backend

# Puerto donde se ejecuta el servidor
server.port=8080

# Conexion a la base de datos MySQL en local
spring.datasource.url=jdbc:mysql://localhost:3306/jobfree?useSSL=false&serverTimezone=UTC
spring.datasource.username=jobfree
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Crea y actualiza las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en consola
spring.jpa.show-sql=true

# Ordena el SQL para que sea mas legible
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=mi_clave_super_segura_de_al_menos_32_caracteres